apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: certificate-job-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: rezzell.com/certificate-job-operator-catalog:v0.1.0
  displayName: Certificate Job Operator Catalog
  publisher: certificate-job-operator
  updateStrategy:
    registryPoll:
      interval: 15m
