apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certificatejob-owner
rules:
- apiGroups:
  - certificates.rezzell.com
  resources:
  - certificatejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.rezzell.com
  resources:
  - certificatejobs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificatejob-owner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certificatejob-owner
subjects:
- kind: Group
  name: namespace-owners
