name: Workflow Lint

on:
  workflow_call:
    inputs:
      runner_json:
        description: JSON encoded runner selection from choose-runner
        required: true
        type: string

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ${{ fromJson(inputs.runner_json) }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
