name: Workflow Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    name: Validate GitHub Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
