name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # We may have a self-hosted runner available for macOS. Use it if so.
  determine-self-hosted-runner:
    runs-on: ubuntu-latest
    concurrency:
      group: runner-determination
      cancel-in-progress: false
    outputs:
      runner: ${{ steps.determine-self-hosted-runner.outputs.use-runner }}
    steps:
      - name: Wait for possible parallel workflow run job startup lag
        # After runner choice, the job that will use it has unavoidable job startup lag
        # Wait for that job start / runner state change before we choose the runner for this run
        run: sleep 30
      - name: Use self-hosted runner if online and not busy, otherwise public runner
        id: determine-self-hosted-runner
        uses: mikehardy/runner-fallback-action@v1
        with:
          organization: "rezzell"
          # self-hosted runner label is configured in ARC app on runner host
          primary-runner: "galleon-runner-set"
          fallback-runner: "ubuntu-latest"
          primaries-required: 1
          fallback-on-error: true
          # Actions secrets and Dependabot secrets are separate, and this is at org level::
          # https://github.com/organizations/ankidroid/settings/secrets/dependabot
          # https://github.com/organizations/ankidroid/settings/secrets/actions
          github-token: ${{ secrets.REZZELL_ORG_ADMIN_KEY }}
  lint:
    name: Lint (Ubuntu)
    needs: determine-self-hosted-runner
    runs-on: ${{ fromJson(needs.determine-self-hosted-runner.outputs.runner) }}
    steps:
      - name: Clone the code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run linter
        env:
          GOCACHE: /tmp/certjob-go-build-cache
          GOMODCACHE: /tmp/certjob-go-mod-cache
        run: make lint
